apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: postgress-operator
spec:
  components:
    ingressGateways:
      - name: istio-postgresgateway
        enabled: true
        k8s:
          service:
            ports:
            - port: 5432
              targetPort: 5432
              name: tcp-postgres   
              protocol: TCP       
            - name: status-port
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              port: 443
              protocol: TCP
              targetPort: 8443
            - name: tcp
              port: 31400
              protocol: TCP
              targetPort: 31400
            - name: tls
              port: 15443
              protocol: TCP
              targetPort: 15443
  values:
    gateways:
      istio-ingressgateway:
        autoscaleEnabled: false
        env: {}
        name: istio-postgresgateway
        secretVolumes:
        - mountPath: /etc/istio/ingressgateway-certs
          name: ingressgateway-certs
          secretName: istio-ingressgateway-certs
        - mountPath: /etc/istio/ingressgateway-ca-certs
          name: ingressgateway-ca-certs
          secretName: istio-ingressgateway-ca-certs
        type: LoadBalancer
        zvpn: {}
