apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
  namespace: postgres
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pgdata"

